UNIT ChessData;

INTERFACE
USES crt;
PROCEDURE PlayGround;

IMPLEMENTATION
PROCEDURE PlayGround;
 BEGIN
  GOTOXY(10,8);  WRITE ('ษอAอหอBอหอCอหอDอหอEอหอFอหอGอหอHอป');
  GOTOXY(10,9);  WRITE ('1   บ   บ   บ   บ   บ   บ   บ   1');
  GOTOXY(10,10); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,11); WRITE ('2   บ   บ   บ   บ   บ   บ   บ   2');
  GOTOXY(10,12); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,13); WRITE ('3   บ   บ   บ   บ   บ   บ   บ   3');
  GOTOXY(10,14); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,15); WRITE ('4   บ   บ   บ   บ   บ   บ   บ   4');
  GOTOXY(10,16); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,17); WRITE ('5   บ   บ   บ   บ   บ   บ   บ   5');
  GOTOXY(10,18); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,19); WRITE ('6   บ   บ   บ   บ   บ   บ   บ   6');
  GOTOXY(10,20); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,21); WRITE ('7   บ   บ   บ   บ   บ   บ   บ   7');
  GOTOXY(10,22); WRITE ('ฬอออฮอออฮอออฮอออฮอออฮอออฮอออฮอออน');
  GOTOXY(10,23); WRITE ('8   บ   บ   บ   บ   บ   บ   บ   8');
  GOTOXY(10,24); WRITE ('ศอAอสอBอสอCอสอDอสอEอสอFอสอGอสอHอผ');
 END;




BEGIN
END.